let mySprite = sprites.create(img`
    ffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffff
    fffffffffff5ffffffffffffffffffff
    ffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffff
    fff1ffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffff.fffff
    fffff2ffffff4fffffffffffffffffff
    ffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffff
    ffffffffffff7fffffffffffffffffff
    ffffffffffffffffffffffffffffffff
    ffffff3fffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffff
    ffff8fffffffff9fffffffffffffffff
    ffffffffffffffffffffffffffffffff
    ffffffffbfffffffffffffffffffffff
    ffffffffffffffffffffffffffffffff
    fffff6ffffffffffffffffffffffffff
    ffafffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffff
    ffefffffdfffffffffffffffffffffff
    ffffffffffffffffffffffffffffffff
    ffffffffffffffffffcfffffffffffff
    ffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffff
    `, SpriteKind.Player)
